//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD1990.TilosRadio.WP7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD1990.TilosRadio.WP7.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kedves fejlesztő, 
        ///
        ///IdeÍrdAzÜzeneted
        ///
        ///----------------------
        ///Ne törölt ki
        ///{0}
        ///----------------------.
        /// </summary>
        public static string FactoryEmailBody {
            get {
                return ResourceManager.GetString("FactoryEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TilosRadioWP7: .
        /// </summary>
        public static string FactoryEmailSubject {
            get {
                return ResourceManager.GetString("FactoryEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kívánság.
        /// </summary>
        public static string FactoryEmailTitle {
            get {
                return ResourceManager.GetString("FactoryEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factory@td1990.hu.
        /// </summary>
        public static string FactoryEmailTo {
            get {
                return ResourceManager.GetString("FactoryEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mond, hogy milyen jó.
        /// </summary>
        public static string FactoryReviewMessage {
            get {
                return ResourceManager.GetString("FactoryReviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to értékelj.
        /// </summary>
        public static string FactoryReviewTitle {
            get {
                return ResourceManager.GetString("FactoryReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kedves Tilos Rádió!
        ///
        ///IdeÍrdAzÜzeneted
        ///
        ///-----------
        ///Sent from WindowsPhone TilosRadio Application
        ///{0}.
        /// </summary>
        public static string RadioEmailBody {
            get {
                return ResourceManager.GetString("RadioEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RadioEmailSubject {
            get {
                return ResourceManager.GetString("RadioEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webmaster@tilos.hu.
        /// </summary>
        public static string RadioEmailTo {
            get {
                return ResourceManager.GetString("RadioEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to töltöget.
        /// </summary>
        public static string StreamBufferingStarted {
            get {
                return ResourceManager.GetString("StreamBufferingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to töltöget.
        /// </summary>
        public static string StreamBufferingStopped {
            get {
                return ResourceManager.GetString("StreamBufferingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vár.
        /// </summary>
        public static string StreamDefault {
            get {
                return ResourceManager.GetString("StreamDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiba1.
        /// </summary>
        public static string StreamError {
            get {
                return ResourceManager.GetString("StreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiba2.
        /// </summary>
        public static string StreamException {
            get {
                return ResourceManager.GetString("StreamException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to előre tekerés.
        /// </summary>
        public static string StreamFastForwarding {
            get {
                return ResourceManager.GetString("StreamFastForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szünet.
        /// </summary>
        public static string StreamPaused {
            get {
                return ResourceManager.GetString("StreamPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adás.
        /// </summary>
        public static string StreamPlaying {
            get {
                return ResourceManager.GetString("StreamPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hátra tekerés.
        /// </summary>
        public static string StreamRewinding {
            get {
                return ResourceManager.GetString("StreamRewinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vége.
        /// </summary>
        public static string StreamShutdown {
            get {
                return ResourceManager.GetString("StreamShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to áll.
        /// </summary>
        public static string StreamStopped {
            get {
                return ResourceManager.GetString("StreamStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adásrész vége.
        /// </summary>
        public static string StreamTrackEnded {
            get {
                return ResourceManager.GetString("StreamTrackEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kapcsolatban.
        /// </summary>
        public static string StreamTrackReady {
            get {
                return ResourceManager.GetString("StreamTrackReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamUnknown {
            get {
                return ResourceManager.GetString("StreamUnknown", resourceCulture);
            }
        }
    }
}
